# Generated by Django 4.0.4 on 2022-06-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('idProducto', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('clase', models.CharField(max_length=20, verbose_name='Tipo de Mascota')),
                ('stock', models.IntegerField(verbose_name='Stock del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsy.categoria')),
            ],
        ),
    ]
