# Generated by Django 4.0.4 on 2022-06-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
