# Generated by Django 4.0.4 on 2022-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsy', '0003_alter_accesorio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Rut_Cliente', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Id del cliente')),
                ('Nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('Transaciones', models.IntegerField(verbose_name='Transaciones')),
            ],
        ),
    ]
